/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * btnTop.java
 *
 * Created on 17/Dez/2011, 16:31:36
 */
package MinhasClasses;

import javax.swing.JOptionPane;
import Fornecedores.Fornecedor;

/**
 *
 * @author Paulo Silva
 */
public class btnTop extends javax.swing.JPanel
{
    private Fornecedor myFornDAL;
    private Clientes.Cliente myCliente;
    private int tipo;
    
    // fornecedor=1, cliente=2,artigo=3
    public void setTipo(int x)
    {
        this.tipo = x;
    }
    public void setMyForn(Fornecedor f) {

        
    }
    
    public void btnTopNovo(java.awt.event.MouseEvent evt)
    {
        // TODO add your handling code here:
    }
    
    /** Creates new form btnTop */
    public btnTop()
    {
        initComponents();
    }

    public void onNovo(java.awt.event.MouseEvent evt) {
        //JOptionPane.showMessageDialog(this, "Actualizado com sucesso!");
        
    }
    
    public void onEliminar() {}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnLeft = new javax.swing.JButton();
        btnRight = new javax.swing.JButton();

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cross_48.png"))); // NOI18N
        btnEliminar.setText("Eliminar");

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add_48.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoMouseClicked(evt);
            }
        });

        btnLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/arrow_left_48.png"))); // NOI18N

        btnRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/arrow_right_48.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnEliminar)
                .addGap(247, 247, 247)
                .addComponent(btnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, Short.MAX_VALUE)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(btnRight, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                .addComponent(btnLeft, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnNovoMouseClicked
    {//GEN-HEADEREND:event_btnNovoMouseClicked
        switch(tipo)
        {
            case 1: JOptionPane.showMessageDialog(this, "Fornecedor");
                break;
            case 2: break;
            case 3: break;
        }
        this.onNovo(evt);
    }//GEN-LAST:event_btnNovoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRight;
    // End of variables declaration//GEN-END:variables
}
